# Generated by Django 5.1.3 on 2024-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient_alter_product_name_alter_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
